version: "3"
services:
  # Site Front http://127.0.0.1:80
  vitrine-front:
    build:
      context: .docker/node/front
    ports:
      - "80:80"
  # Site Back http://127.0.0.1:3200
  vitrine-back:
    build:
      context: .docker/node/back
    ports:
      - "3200:3200"
  # DB : 3306
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"


